### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kyosuke30** [kyosuke30/furima-39542#22]
# フリマアプリのURL
https://furima-39542.onrender.com/

# Basic認証のIDとパスワード
ID：furima
パスワード：39542

# 出品者用のメールアドレスとパスワード
メールアドレス：test1@test.com
パスワード：test11

# 購入者用のメールアドレスとパスワード
メールアドレス：test2@test.com
パスワード：test22

**Comment by shodai-ito** [comment]
@kyosuke30 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
価格を入力しても手数料と利益が表示されません。

- [x] **クレジットカードの情報は購入の都度入力させること**
一度購入に失敗すると、それ以降クレジットカード情報が入力できなくなってしまいます。

- [x] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
都道府県の情報がなくても購入できてしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
一度出品に失敗すると、それ以降入力しても販売手数料と販売利益が表示されなくなってしまいます。
どの段階でも表示されるよう修正しましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A
